/*
 *
 *  Copyright (c) 2026 Ayaan.
 *  Licensed under the MIT License.
 *
 *  Created: 2026
 *  Modified: 3/18/26, 10:17 PM
 *
 *  AgentVerse
 *  Integrates multiple AI models with a modular clean architecture.
 *
 *
 */

package com.atech.api_integration_common.model

import androidx.annotation.Keep
import kotlinx.serialization.Serializable

/**
 * Represents the configuration settings for an AI model in the AgentVerse system,
 * including parameters that influence the behavior of the model during response generation.
 * This structure allows for fine-tuning the model's output based on specific requirements, such as
 * temperature for controlling randomness, maxTokens for limiting response length, and other parameters that affect the diversity and relevance of the generated responses.
 * @param temperature Controls the randomness of the model's output. Higher values (e.g.,
 * 0.8) make the output more random, while lower values (e.g., 0.2) make it more focused and deterministic.
 * @param maxTokens Limits the maximum number of tokens in the generated response, helping to control
 * the length of the output.
 * @param topP Controls the diversity of the output by limiting the cumulative probability of the most
 * likely tokens. A value of 0.9 means that only the tokens that together have a cumulative probability of 90% will be considered for generation.
 * @param frequencyPenalty Penalizes new tokens based on their existing frequency in the text so far, reducing the likelihood of repeating the same token.
 * @param presencePenalty Penalizes new tokens based on whether they appear in the text so far, encouraging the model to talk about new topics.
 * @param steam Enables or disables streaming responses, allowing for real-time output generation.
 * @param stopSequences A list of strings that, when generated by the model, will signal
 * the end of the response, allowing for more controlled output and preventing the model from generating unwanted text.
 * @see AvModel
 * @see AvRequest
 * @see AvMessage
 * @see Role
 */
@Keep
@Serializable
data class AvModelConfig(
    val modelName: String = "default",
    val configDescription : String = "Default model configuration",
    val modelVersion: String = "1.0",
    val temperature: Double = 0.7,
    val maxTokens: Int = 100,
    val topP: Double = 1.0,
    val frequencyPenalty: Double = 0.0,
    val presencePenalty: Double = 0.0,
    val steam: Boolean = false,
    val stopSequences: List<String> = emptyList()
)

