/*
 *
 *  Copyright (c) 2026 Ayaan.
 *  Licensed under the MIT License.
 *
 *  Created: 2026
 *  Modified: 3/22/26, 1:50 PM
 *
 *  AgentVerse
 *  Integrates multiple AI models with a modular clean architecture.
 *
 *
 */

package com.atech.api_integration_common.model.response

import androidx.annotation.Keep
import kotlinx.serialization.Serializable

/**
 * Represents the response from an AI model, including metadata about the response and the generated content.
 * This structure allows for a standardized way to handle responses from different AI models, facilitating easier integration and processing of the results.
 * @param id A unique identifier for the response.
 * @param objectType The type of object returned (e.g., "response").
 * @param usage Metadata about the usage of tokens and time taken for processing the request.
 * @param serviceTier The service tier used for this response (e.g., "free", "premium").
 * @param model The specific AI model that generated the response.
 * @param created The timestamp when the response was created.
 * @param choices A list of choices generated by the model, each containing a message and additional information about the choice.
 */
@Keep
@Serializable
data class AvResponse(
    val id: String,
    val objectType: String,
    val usage : Usage,
    val serviceTier : String,
    val model: String,
    val created : Long,
    val choices: List<Choice>
)

/**
 * Represents the usage metadata for an AI response, including information about token counts and processing times.
 * This structure provides insights into the resources consumed during the generation of the response, which can be useful for monitoring and optimizing API usage.
 * @param queueTime The time spent in the queue before processing the request.
 * @param promptTokens The number of tokens in the input prompt.
 * @param promptTime The time taken to process the input prompt.
 * @param completionTokens The number of tokens in the generated completion.
 * @param completionTime The time taken to generate the completion.
 * @param totalTokens The total number of tokens used (prompt + completion).
 * @param totalTime The total time taken for the entire request (queue + prompt processing + completion generation).
 */
@Keep
@Serializable
data class Usage(
    val queueTime: Double,
    val promptTokens: Int,
    val promptTime: Double,
    val completionTokens: Int,
    val completionTime: Double,
    val totalTokens: Int,
    val totalTime: Double
)

/**
 * Represents a single choice generated by the AI model, including the message content and additional information about the choice.
 * This structure allows for multiple choices to be returned in a single response, enabling more flexible interactions
 * with the AI model and providing users with options to select from.
 * @param message The message content generated by the AI model, including the role and content of the message.
 * @param finishReason The reason why the generation of this choice was finished (e.g., "stop", "length").
 * @param index The index of this choice in the list of choices returned by the model.
 * @see Message
 */
@Keep
@Serializable
data class Choice(
    val message: Message,
    val finishReason: String,
    val index: Int
)

/**
 * Represents a message generated by the AI model, including the role of the sender and the content of the message.
 * This structure allows for a clear distinction between different types of messages in the dialogue, facilitating better
 * context management and response generation when processing the choices returned by the AI model.
 * @param role The role of the message sender (e.g., "assistant", "user
 * ").
 * @param content The actual text content of the message generated by the AI model.
 * @see Choice
 * @see AvResponse
 */
@Keep
@Serializable
data class Message(
    val role: String,
    val content: String
)