/*
 *
 *  Copyright (c) 2026 Ayaan.
 *  Licensed under the MIT License.
 *
 *  Created: 2026
 *  Modified: 3/22/26, 1:58 PM
 *
 *  AgentVerse
 *  Integrates multiple AI models with a modular clean architecture.
 *
 *
 */

package com.atech.api_integration_common.model.request

import androidx.annotation.Keep
import kotlinx.serialization.Serializable

/**
 * Represents a request to the AgentVerse system,
 * containing the necessary information.
 * model to be used for processing the request and a list of messages that form the conversation context.
 * This structure allows for a clear and organized way to send requests to the system, ensuring that
 * the appropriate model is utilized and that the conversation history is maintained for accurate response generation.
 * @param model The AI model to be used for processing the request.
 * @param message A list of messages that form the conversation context, including the role of the
 * @param modelConfig The configuration settings for the model, allowing for fine-tuning of the response generation process based on specific requirements.
 * @see AvModel
 * @see AvMessage
 * @see AvModelConfig
 * @see OutputSettings
 */
@Keep
@Serializable
data class AvRequest(
    val model : AvModel,
    val message : List<AvMessage>,
    val modelConfig: AvModelConfig = AvModelConfig(),
    val outputSettings: OutputSettings = OutputSettings()
)


/**
 * Represents a model available in the AgentVerse system,
 * including its metadata and capabilities.
 */
@Keep
@Serializable
data class AvModel(
    val modelId: String,
    val ownedBy: String,
    val isActive: Boolean,
    val contextWindow: Int,
    val created: Long
)


/**
 * Defines the role of the
 * message sender in the conversation.
 * - USER: The end-user interacting with the system.
 * - ASSISTANT: The AI assistant responding to the user.
 * - SYSTEM: System-level messages, such as instructions or metadata.
 */
enum class Role{
    USER,
    ASSISTANT,
    SYSTEM
}

/**
 * Represents a single message in the conversation, including the sender's role and the content of the message.
 * This structure allows for a clear distinction between different types of messages in the dialogue, facilitating better context management and response generation.
 * @param role The role of the message sender (USER, ASSISTANT, SYSTEM).
 * @param content The actual text content of the message.
 * @see Role
 */
@Keep
@Serializable
data class AvMessage(
    val role: Role,
    val content: String
)


/**
 * Represents the configuration settings for an AI model in the AgentVerse system,
 * including parameters that influence the behavior of the model during response generation.
 * This structure allows for fine-tuning the model's output based on specific requirements, such as
 * temperature for controlling randomness, maxTokens for limiting response length, and other parameters that affect the diversity and relevance of the generated responses.
 * @param temperature Controls the randomness of the model's output. Higher values (e.g.,
 * 0.8) make the output more random, while lower values (e.g., 0.2) make it more focused and deterministic.
 * @param maxTokens Limits the maximum number of tokens in the generated response, helping to control
 * the length of the output.
 * @param topP Controls the diversity of the output by limiting the cumulative probability of the most
 * likely tokens. A value of 0.9 means that only the tokens that together have a cumulative probability of 90% will be considered for generation.
 * @param frequencyPenalty Penalizes new tokens based on their existing frequency in the text so far, reducing the likelihood of repeating the same token.
 * @param presencePenalty Penalizes new tokens based on whether they appear in the text so far, encouraging the model to talk about new topics.
 * @param stopSequences A list of strings that, when generated by the model, will signal
 * the end of the response, allowing for more controlled output and preventing the model from generating unwanted text.
 * @see AvModel
 * @see AvRequest
 * @see AvMessage
 * @see Role
 */
@Keep
@Serializable
data class AvModelConfig(
    val modelName: String = "default",
    val configDescription : String = "Default model configuration",
    val modelVersion: String = "1.0",
    val temperature: Double = 0.7,
    val maxTokens: Int = 100,
    val topP: Double = 1.0,
    val frequencyPenalty: Double = 0.0,
    val presencePenalty: Double = 0.0,
    val stopSequences: List<String> = emptyList()
)


/**
 * Represents the output settings for an AI model response in the AgentVerse system,
 * allowing for configuration of how the output should be generated and delivered.
 * This structure provides a way to specify whether the response should be streamed in real-time or delivered as a complete output, enabling more flexible and efficient handling of responses based on the specific requirements of the application or use case.
 * @param stream A boolean flag indicating whether the response should be streamed in real-time (true) or delivered as a complete output (false).
 * @Param memorySize An integer specifying the size of the memory buffer for storing conversation history, which can be used to maintain context across multiple interactions with the AI model.
 * @see AvModelConfig
 * @see AvRequest
 * @see AvMessage
 */
@Keep
@Serializable
data class OutputSettings(
    val stream: Boolean = false,
    val memorySize : Int = 5
)

